import fs from 'fs';
import path from 'path';
import { INDEX_FILE } from './agentHook';

// Turingram's whole claim is that your meetings are readable by your own tools.
// That claim is only true if someone can find out where they are, and the answer
// has to travel with the folder — because the folder is what moves.
//
// An agent pointed at a directory of JSON reads what is there; it does not know
// what the fields mean, that index.json exists, or that "You" is a real speaker
// label rather than a placeholder. Documentation kept anywhere else is
// documentation it will never see. A README in the folder is read by whatever
// tool arrives, including tools this app has never heard of, and it survives the
// user moving the folder into their vault.

export const README_FILE = 'README.md';

export function buildReadme(dir: string): string {
  return `# Turingram transcripts

Machine-readable transcripts of this user's meetings, written by Turingram.
Nothing here is generated by an agent — it is recorded audio, transcribed and
speaker-separated. Treat it as a primary source.

Location: \`${dir}\`

## Start with ${INDEX_FILE}

\`${INDEX_FILE}\` lists every meeting, newest first, so you can find the one you
want without opening anything else:

\`\`\`json
{
  "count": 12,
  "meetings": [
    {
      "id": "3f2a9c1e-5b7d-4e8a-9c0f-1d2e3f4a5b6c",
      "file": "2026-07-31-quarterly-planning-1231-1302.json",
      "title": "Quarterly planning",
      "date": "2026-07-31T19:31:04.000Z",
      "startedAt": 1785526264000,
      "durationSec": 1552,
      "speakers": ["You", "Avery", "Blake"]
    }
  ]
}
\`\`\`

Filenames follow \`YYYY-MM-DD-title-slug-HHMM-HHMM.json\` (date, title, start and
end clock times), so date and topic are usually enough to pick a file directly.
An export of the same meeting in the user's Downloads folder carries the same
base name with a different extension.

## Transcript shape

\`\`\`json
{
  "id": "3f2a9c1e-...",
  "title": "Quarterly planning",
  "startedAt": 1785526264000,
  "endedAt": 1785528118000,
  "durationSec": 1552,
  "notes": "user's own notes, may be empty",
  "summary": "may be absent",
  "actionItems": ["may be absent"],
  "segments": [
    { "speaker": "You", "startTime": 0.0, "endTime": 4.2, "text": "..." }
  ]
}
\`\`\`

- \`startedAt\` / \`endedAt\` are epoch milliseconds. \`startTime\` / \`endTime\` are
  **seconds from the start of the recording**, not wall-clock.
- \`durationSec\` is trimmed to actual speech, so it can be shorter than
  \`endedAt - startedAt\`. Prefer it when reporting how long a meeting ran.
- \`speaker\` is a display name once the user has assigned one, and \`Speaker 1\`,
  \`Speaker 2\` … until then.
- **\`You\` is the user**, identified from the microphone channel rather than
  guessed. When you summarise, that is the person you are talking to.
- \`summary\` and \`actionItems\` are absent on meetings that were never summarised.
  Absent means not generated, not "none".

## Notes

- Files are written atomically and rewritten in place whenever the user edits a
  title, notes, or speaker names — so re-read rather than caching, and expect a
  meeting's filename to change if its title does. \`id\` is stable; the filename
  is not.
- A meeting deleted in the app is deleted here, audio and all. If it is gone,
  the user removed it.
- The user chooses this folder, so it may be one of their own — a notes vault, a
  project directory. Anything not listed in \`${INDEX_FILE}\` is theirs, not
  Turingram's, and this file says nothing about it.
- This file is regenerated by Turingram on launch. Edits to it will be lost.
`;
}

export function writeAgentReadme(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
  const dest = path.join(dir, README_FILE);
  const content = buildReadme(dir);
  // Only rewrite on change, so a folder someone is watching stays quiet.
  try {
    if (fs.readFileSync(dest, 'utf8') === content) return;
  } catch { /* not there yet */ }
  fs.writeFileSync(dest, content);
}
